import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// @ts-expect-error: Importing global CSS in Next.js app directory is not typed
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-slate-900 via-gray-700 to-gray-950 `}
      >
        {children}
      </body>
    </html>
  );
}
