import type { Metadata } from 'next';
import './globals.css'


export const metadata: Metadata = {
  title: 'Space Saboteur',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-linear-to-br from-slate-900 via-gray-700 to-gray-950">
        {children}
      </body>
    </html>
  );
}
